name: Deploy vATIS Airports.json to GVSC

on:
  push:
    paths:
      - "vatis/airports-json/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #    container:
    #      pandoc/latex # "ubuntu" is a more generic container
    # using "pandoc/latex" because of dependencies
    # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: |
          mkdir output
          cp -r vatis/airports-json output
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: vatis/airports-json
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-gvsc"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: vatis
          target-directory: "Plugins/vATIS Profile/Airports"
          create-target-branch-if-needed: true
          commit-message: "update: vatis airports.json"
