name: Deploy Issue Templates to GVSC

on:
  push:
    paths:
      - "repository-management/templates/issues/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #    container:
    #      pandoc/latex # "ubuntu" is a more generic container
    # using "pandoc/latex" because of dependencies
    # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: |
          mkdir output
          cp -r vatis/airports-json output
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-gvsc"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".gitub/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: issue templates"
